### PR TITLE
Adapt Julia files to use the Base.Test module for tests

### PR DESCRIPTION
**Pull request by lbenet**
ValidatedNumerics was using FactCheck.jl package, but now uses
Base.Test.
See [https://github.com/dpsanders/ValidatedNumerics.jl/pull/205]

### CODE REVIEW

**Comment by lbenet** [comment]
@oheim Thank's for reacting to this.

While we are considering using the Base.Test module, there seem to be issues regarding the time of execution which is stopping us to go further. Tests are passing locally, but take extremely long time! So maybe we should leave this waiting some time.

**Comment by oheim** [comment]
Okay. We can merge the request and you are free to choose the old plugin, right?

**Comment by lbenet** [comment]
As you prefer. Simply, we are delaying changing the test modules because of the time it takes. We are making some tests with parallelization, but some tests simply take much too long... How do you choose which plugin to use?

**Comment by oheim** [comment]
You may run the generator with
- either `python3 -m itf1788 -c "(julia, Base.Test, ValidatedNumerics.jl)`
- or `python3 -m itf1788 -c "(julia, FactCheck, ValidatedNumerics.jl)`

**Comment by lbenet** [comment]
Great! Thanks!

**Pull request merged**
